env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
parser: typescript-eslint-parser
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
  semi:
    - error
    - always
