# Logs level // error / warn / info / verbose / debug / silly
logsLevel:
  console: 'silly'

# Bcrypt salt rounds
saltRounds: 10

# Winston logs level
winston:
  levels:
    error: 0
    warn: 1
    info: 2
    verbose: 3
    debug: 4
    data: 5
    silly: 6
  colors:
    error: 'red'
    warn: 'yellow'
    info: 'green'
    verbose: 'cyan'
    debug: 'blue'
    data: 'magenta'
    silly: 'grey'

# Paths
paths:
  script: './src/views/script'
  style: './src/views/style'
  image: './src/views/image'
  imageList: './src/views/image/images.json'