# Clone this file in 'config.dev.yml' or 'config.prod.yml' and edit it according to your environement

# Website informations
website:
  title: "Draw Me Something"

# Server informations
server:
  host: 'localhost'
  port: 8001

# Mongoose
mongoose:
  connectionString: 'mongodb://localhost/dawme'

# Images informations
imagesPath: './images'
imagesList: './images/images.json'

# Language
language: 
  locales: ["en"]
  default: "en"

# Security
security:
  sessionSecret: 'foobar'
  passwordSaltFactor: 10